mod variable;
mod operators ;
mod boolen ;
mod if_else ;
mod matchs ;
mod loops ;
mod strings ;
mod ownership ;
mod borrow ;
mod arrays ;
mod vectors;
mod turples ;
mod hashmap;
mod structss;
// mod variables;
fn main() {
    println!("Hello, world!");
    variable::run();
    variable::runn();
    operators::operator();
    boolen :: bool();
    if_else :: com ();
    matchs :: much ();
    loops :: lop();
    strings :: stri();
    ownership::own();
    borrow::borro();
    arrays::array();
    vectors::vector();
    turples::turple();
    hashmap::hashmaps();
    structss::structs();
}
